nti_notification:
    resource: "@NotificationBundle/Controller/"
    type:     annotation
    prefix: /nti/notify/
#    prefix: /{_prefix}/
#    requirements:
#        _prefix: "%nti.notification.route.prefix%"